-
  model: 'output/en-de-model_epoch5_20.44.t7'
  replace_unk: true
  mode: aggressive
  joiner_annotate: true
  case_feature: true
  segment_case: true
  beam_size: 5

#-
#  model: '/NMTModels/en-it/model-enit_epoch600_4.17.t7'
#  replace_unk: true
#  mode: aggressive
#  joiner_annotate: true
#  case_feature: true
#  segment_case: true
#  beam_size: 5