-
 model: 'output/en-de-model_epoch13_6.62_release.t7'
 replace_unk: true
 mode: aggressive
 joiner_annotate: true
 case_feature: true
 segment_case: true
 beam_size: 5

-
 model: 'output/en-fr-model_epoch13_3.07_release.t7'
 replace_unk: true
 mode: aggressive
 joiner_annotate: true
 case_feature: true
 segment_case: true
 beam_size: 5

-
 model: 'output/en-es-model_epoch13_5.68_release.t7'
 replace_unk: true
 mode: aggressive
 joiner_annotate: true
 case_feature: true
 segment_case: true
 beam_size: 5